#!/usr/bin/env python3
"""backfill.py — Run editor_review against EVERY past issue.

Brian's standing rule (2026-05-30): no grandfathering. An investor may audit
any issue at any time. They all must meet every standard.

Produces:
  - Per-issue gate result table
  - Aggregate (which gates fail most often → root-cause investigation)
  - `_engine/BACKFILL-REPORT.md` written for vault reference

Usage:
    python3 _engine/scripts/backfill.py             # audit every issue in archive/
    python3 _engine/scripts/backfill.py 2026-05     # only May 2026
"""
import sys, subprocess, pathlib, re
from datetime import datetime, timezone
from collections import defaultdict

REPO = pathlib.Path(__file__).resolve().parents[2]
EDITOR = REPO / "_engine" / "scripts" / "editor_review.py"

def gather_issues(prefix: str = "") -> list[pathlib.Path]:
    out = []
    for p in sorted((REPO / "archive").glob("*.html")):
        if not re.match(r"\d{4}-\d{2}-\d{2}-.+\.html$", p.name): continue
        if prefix and not p.name.startswith(prefix): continue
        out.append(p)
    return out

GATE_RE = re.compile(r"^\s*(✅|❌|⚠️|⊘)\s+([A-Za-z0-9 +(),—\-≥/.]+?)\s+\[", re.MULTILINE)

def run_editor(issue: pathlib.Path) -> tuple[int, dict]:
    r = subprocess.run(["python3", str(EDITOR), str(issue), "--skip-links"], capture_output=True, text=True)
    results = {}
    for m in GATE_RE.finditer(r.stdout):
        sym, name = m.group(1), m.group(2).strip()
        results[name] = sym
    return r.returncode, results

def main():
    prefix = sys.argv[1] if len(sys.argv) > 1 else ""
    issues = gather_issues(prefix)
    if not issues:
        print(f"No issues found (prefix='{prefix}')"); sys.exit(0)

    print(f"Backfilling {len(issues)} issue(s)...\n")
    per_issue = []
    gate_fails = defaultdict(int)
    gate_warns = defaultdict(int)
    gate_seen = set()
    blocked = warned = ready = 0

    for issue in issues:
        code, gates = run_editor(issue)
        if code == 0: ready += 1
        elif code == 1: blocked += 1
        elif code == 2: warned += 1
        per_issue.append((issue.name, code, gates))
        for name, sym in gates.items():
            gate_seen.add(name)
            if sym == "❌": gate_fails[name] += 1
            elif sym == "⚠️": gate_warns[name] += 1
        print(f"  {('✅' if code==0 else '❌' if code==1 else '⚠️')} {issue.name}  → "
              f"{sum(1 for s in gates.values() if s=='❌')} fail · "
              f"{sum(1 for s in gates.values() if s=='⚠️')} warn")

    # Markdown report
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    md = [
        f"# Backfill Report — {now}",
        f"*Generated by `_engine/scripts/backfill.py {prefix or ''}` against {len(issues)} issue(s).*",
        f"",
        f"## Summary",
        f"- Ready (every gate passes): **{ready}**",
        f"- Soft-warned (regression — hard pass, soft warn): **{warned}**",
        f"- Blocked (hard fail): **{blocked}**",
        f"",
        f"## Failure frequency across all issues",
        f"",
        f"| Gate | Fails | Warns |",
        f"|------|-------|-------|",
    ]
    for name in sorted(gate_seen, key=lambda n: (-gate_fails[name], -gate_warns[name], n)):
        md.append(f"| {name} | {gate_fails[name]} | {gate_warns[name]} |")
    md += ["", "## Per-issue verdict", "", "| Issue | Verdict | Fails | Warns |", "|-------|---------|-------|-------|"]
    for name, code, gates in per_issue:
        verdict = "ready" if code == 0 else "BLOCKED" if code == 1 else "warn"
        nf = sum(1 for s in gates.values() if s == "❌")
        nw = sum(1 for s in gates.values() if s == "⚠️")
        md.append(f"| {name} | {verdict} | {nf} | {nw} |")

    report = REPO / "_engine" / "BACKFILL-REPORT.md"
    report.write_text("\n".join(md))
    print(f"\n→ Report: {report}")
    print(f"  Ready: {ready} · Warned: {warned} · Blocked: {blocked}")

    # If most issues fail the same gate, it's likely a single root cause
    top = sorted(gate_fails.items(), key=lambda kv: -kv[1])[:3]
    if top:
        print(f"\nTop failure modes (likely root-cause patterns):")
        for name, count in top:
            print(f"  {count:3} × {name}")

if __name__ == "__main__":
    main()
